Interfaces updated
okta/okta-management-openapi-spec pull request #40
Opened 2021-04-02 08:43 UTC by sergiishamrai-okta

`OktaSignOnPolicyRuleActions` and `PasswordPolicyRuleActions` should implement `PolicyRuleActions`
`OktaSignOnPolicyRuleConditions` and `PasswordPolicyRuleConditions` should implement `PolicyRuleConditions`

2021-04-02 17:21 UTC, arvindkrishnakumar-okta approved these changes

2021-04-05 15:43 UTC, laura-rodriguez commented
@arvindkrishnakumar-okta have you tried these changes in Java?
@sergiishamrai-okta can you explain why do we need these changes for context? Thanks!

2021-04-05 19:32 UTC, arvindkrishnakumar-okta commented
> @arvindkrishnakumar-okta have you tried these changes in Java?
> @sergiishamrai-okta can you explain why do we need these changes for context? Thanks!

@sergiishamrai-okta has tested this.

2021-04-06 12:27 UTC, serhiibuniak-okta approved these changes

2021-04-19 13:15 UTC, bryanapellanes-okta reviewed
@sergiishamrai-okta this looks fine to me but I think @bretterer has deeper knowledge as to the potential side effects of this.

2021-04-19 13:18 UTC, bretterer requested changes
This looks right, but we need more information on why this change is needed. What is the current issue with this and what is this solving. Who is asking for it. etc...

2021-04-19 13:56 UTC, bretterer approved these changes
This looks fine.  I am concerned that we are getting a lot of updates to the spec that only are affecting Java. We should discuss as a team why this is.

2021-04-26 07:54 UTC, merged