Added operations for Group Schema
okta/okta-management-openapi-spec pull request #68
Opened 2021-08-20 12:59 UTC by bogdanprodan-okta

[Official Documentation](https://developer.okta.com/docs/reference/api/schemas/#group-schema-operations) might be missing some of the fields (sam as for UserSchema)

2021-08-20 15:22 UTC, monde approved these changes

2021-08-20 16:52 UTC, arvindkrishnakumar-okta requested changes
@bogdanprodan-okta Can you add IT coverage for these endpoints in your SDK before we merge this PR?

2021-08-29 14:45 UTC, bogdanprodan-okta commented
> @bogdanprodan-okta Can you add IT coverage for these endpoints in your SDK before we merge this PR?

@arvindkrishnakumar-okta I've added the tests and they are working fine when I use my terraform test org, but fail with `you don't have permissions for this action` error in test-org `https://sdk-test.trexcloud.com`

2021-08-30 14:42 UTC, sergiishamrai-okta commented
Works fine in Java Mgmt SDK

2021-08-30 14:42 UTC, sergiishamrai-okta approved these changes

2021-08-30 14:50 UTC, arvindkrishnakumar-okta approved these changes

2021-08-30 14:51 UTC, merged